import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';
import './globals.css';
import { Toaster } from 'react-hot-toast';

const dmSans = DM_Sans({
   variable: '--font-dm-sans',
   subsets: ['latin'],
});

// ${dmSans.variable}

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="es" className={`h-full antialiased ${dmSans.variable}`}>
         <body className="min-h-full flex flex-col">
            {children}
            <Toaster position="bottom-right" />
         </body>
      </html>
   );
}
